runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: './key.json'
  INSTANCE_CONNECTION_NAME: 'mysql-animal-adoption-app:us-central1:animal-adoption-app-instance'
  DB_NAME: 'animal-adoption-app-db'
  DB_USER: 'group-member'
  DB_PASS: '0467'