runtime: python39

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: './key.json'
  INSTANCE_CONNECTION_NAME: 'mysql-animal-adoption-app:us-central1:animal-adoption-app-instance'
  DB_NAME: 'animal-adoption-app-db'
  DB_USER: 'group-member'
  DB_PASS: '0467'